CREATE TABLE `characters` (
	`id` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`level` int NOT NULL DEFAULT 1,
	`experiencePoints` int NOT NULL DEFAULT 0,
	`species` enum('humano','homem-peixe','mink','celestial','gigante','anao','lunariano','mestico') NOT NULL,
	`combatStyle` enum('lutador','espadachim','atirador','ninja','ciborgue','guerrilheiro','okama-kenpo','rokushiki','guerreiro-oni','carateca-homem-peixe') NOT NULL,
	`profession` enum('cozinheiro','medico','navegador','timoneiro','carpinteiro','engenheiro','musico','arqueólogo','adestrador','combatente','cacador-recompensas'),
	`appearance` text,
	`personality` text,
	`dream` text,
	`philosophy` text,
	`background` text,
	`attributes` json NOT NULL,
	`skills` json NOT NULL,
	`proficiencies` json,
	`maxHealth` int NOT NULL DEFAULT 10,
	`currentHealth` int NOT NULL DEFAULT 10,
	`maxPowerPoints` int NOT NULL DEFAULT 5,
	`currentPowerPoints` int NOT NULL DEFAULT 5,
	`exhaustionLevel` int NOT NULL DEFAULT 0,
	`armorClass` int NOT NULL DEFAULT 10,
	`proficiencyBonus` int NOT NULL DEFAULT 2,
	`haki` json,
	`ambitionPoints` int NOT NULL DEFAULT 0,
	`maxAmbitionPoints` int NOT NULL DEFAULT 0,
	`akumaNoMi` json,
	`weapons` json,
	`armor` varchar(255),
	`items` json,
	`bellys` decimal(15,0) NOT NULL DEFAULT '0',
	`trainings` json,
	`masteries` json,
	`bounty` decimal(15,0) NOT NULL DEFAULT '0',
	`crewName` varchar(255),
	`crewRole` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `characters_id` PRIMARY KEY(`id`)
);
